version: '3.3'

services:

    cervantes-db:
        container_name: cervantes-db
        image: postgres:latest
        restart: unless-stopped
        expose:
            - "5432"
        environment:
            POSTGRES_DATABASE: cervantes
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: p4ssw0rd 

    cervantes-app:
        container_name: cervantes-app
        image: mesq/cervantes
        depends_on: 
            - cervantes-db
        restart: unless-stopped
        expose:
            - "80"
            - "443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - ./appsettings.json:/app/appsettings.json

    cervantes-nginx:
        container_name: cervantes-nginx
        image: nginx:latest
        depends_on:
            - cervantes-app
        restart: unless-stopped
        ports:
            - "8200:80"
            - "8443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
    
